<?php

/**
 * @file
 * USA Search hosted search.
 */

/**
 * Implements hook_menu_alter().
 */
function usasearch_hosted_menu_alter(&$items) {
  $items['search'] = array(
    'access arguments' => array('search content'),
    'description' => 'Search Results',
    'page callback' => 'usasearch_hosted_redirect',
    'type' => MENU_CALLBACK,
    'file' => drupal_get_path('module', 'usasearch_hosted') . '/usasearch_hosted.inc',
  );
  $items['search/%'] = array(
    'access arguments' => array('search content'),
    'description' => 'Search Results',
    'page callback' => 'usasearch_hosted_redirect',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'file' => drupal_get_path('module', 'usasearch_hosted') . '/usasearch_hosted.inc',
  );
}

/**
 * Implements hook_form_alter().
 *
 * Changes elements in the search block, search theme form, search page form.
 */
function usasearch_hosted_form_alter(&$form, &$form_state, $form_id) {
  // Search block and search box have similar form structure.
  if ($form_id == 'search_block_form'
    || $form_id == 'search_theme_form'
    || $form_id == 'search_form'
    || $form_id == 'usasearch_hosted_box'
    || strpos($form_id, 'usasearch_field_search_box_') !== FALSE
  ) {
    $action_domain = check_plain(variable_get('usasearch_action_domain', 'https://search.usa.gov'));
    $affiliate_name = check_plain(variable_get('usasearch_affiliate_name', ''));

    // Set action method, location and read affiliate from variable.
    $form['#method'] = 'get';
    $parsed = parse_url($action_domain);
    if (empty($parsed['scheme'])) {
      $action_domain = 'https://' . ltrim($action_domain, '/');
    }
    $form['#action'] = $action_domain . '/search';

    $form['affiliate']['#type'] = 'hidden';
    // Check for affiliate_name variable before printing the affiliate form
    // element. We also first check that usasearch_field has not already set
    // the affiliate.
    if ($affiliate_name && empty($form['affiliate']['#value'])) {
      $form['affiliate']['#value'] = $affiliate_name;
    }

    // Remove unnecessary, hidden input fields.
    unset($form['form_build_id']);
    unset($form['form_token']);
    unset($form['form_id']);

    if ($form_id == 'search_form') {
      // Change text field name to query.
      $form['basic']['keys']['#attributes']['name'] = 'query';
      // Unset 'advanced' fieldset.
      unset($form['advanced']);
    }
    else {
      // Change text field name to query.
      $form[$form_id]['#attributes']['name'] = 'query';
    }
  }
}

/**
 * Implements hook_permission().
 */
function usasearch_hosted_permission() {
  return array(
    'use usasearch hosted block' => array(
      'title' => t('Use the DigitalGov USA Search block'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function usasearch_hosted_block_info() {
  $blocks['form']['info'] = t('USA Search form');
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function usasearch_hosted_block_view($delta = '') {
  if (user_access('use usasearch hosted block')) {
    $block['content'] = drupal_get_form('usasearch_hosted_box', NULL, NULL);
  }
  
  return $block;
}

/**
 * Form builder; Output a search form for the search block's search box.
 *
 * @ingroup forms
 * @see usasearch-hosted-block-form.tpl.php
 */
function usasearch_hosted_box($form, &$form_state, $form_id) {
  if (empty($form_id)) {
    $form_id = 'usasearch_hosted_box';
  }
  
  $form[$form_id] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#title_display' => 'invisible',
    '#size' => 15,
    '#default_value' => '',
    '#attributes' => array(
      'name' => 'query'
    ),  
  );
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Search'));
  
  return $form;
}

/**
 * Implements hook_theme().
 */
function usasearch_hosted_theme() {
  return array(
    'usasearch_hosted_box' => array(
      'render element' => 'form',
      'template' => 'usasearch-hosted-block-form',
    ),
  );
}

/**
 * Process variables for search-block-form.tpl.php.
 *
 * The $variables array contains the following arguments:
 * - $form
 *
 * @see usasearch-hosted-block-form.tpl.php
 */
function template_preprocess_usasearch_hosted_box(&$variables) {
  $variables['usasearch'] = array();
  $hidden = array();

  // Provide variables named after form keys so themers can print each element independently.
  foreach (element_children($variables['form']) as $key) {
    $type = isset($variables['form'][$key]['#type']) ? $variables['form'][$key]['#type'] : '';
    if ($type == 'hidden' || $type == 'token') {
      $hidden[] = drupal_render($variables['form'][$key]);
    }
    else {
      $variables['usasearch'][$key] = drupal_render($variables['form'][$key]);
    }
  }
  // Hidden form elements have no value to themers. No need for separation.
  $variables['usasearch']['hidden'] = implode($hidden);
  // Collect all form elements to make it easier to print the whole form.
  
  $variables['usasearch_form'] = implode($variables['usasearch']);
}
